init python:
    class RpgmConstants:
        ROUTE_COMMAND_NAMES = {
            0: "ROUTE_END",
            1: "ROUTE_MOVE_DOWN",
            2: "ROUTE_MOVE_LEFT",
            3: "ROUTE_MOVE_RIGHT",
            4: "ROUTE_MOVE_UP",
            5: "ROUTE_MOVE_LOWER_L",
            6: "ROUTE_MOVE_LOWER_R",
            7: "ROUTE_MOVE_UPPER_L",
            8: "ROUTE_MOVE_UPPER_R",
            9: "ROUTE_MOVE_RANDOM",
            10: "ROUTE_MOVE_TOWARD",
            11: "ROUTE_MOVE_AWAY",
            12: "ROUTE_MOVE_FORWARD",
            13: "ROUTE_MOVE_BACKWARD",
            14: "ROUTE_JUMP",
            15: "ROUTE_WAIT",
            16: "ROUTE_TURN_DOWN",
            17: "ROUTE_TURN_LEFT",
            18: "ROUTE_TURN_RIGHT",
            19: "ROUTE_TURN_UP",
            20: "ROUTE_TURN_90D_R",
            21: "ROUTE_TURN_90D_L",
            22: "ROUTE_TURN_180D",
            23: "ROUTE_TURN_90D_R_L",
            24: "ROUTE_TURN_RANDOM",
            25: "ROUTE_TURN_TOWARD",
            26: "ROUTE_TURN_AWAY",
            27: "ROUTE_SWITCH_ON",
            28: "ROUTE_SWITCH_OFF",
            29: "ROUTE_CHANGE_SPEED",
            30: "ROUTE_CHANGE_FREQ",
            31: "ROUTE_WALK_ANIME_ON",
            32: "ROUTE_WALK_ANIME_OFF",
            33: "ROUTE_STEP_ANIME_ON",
            34: "ROUTE_STEP_ANIME_OFF",
            35: "ROUTE_DIR_FIX_ON",
            36: "ROUTE_DIR_FIX_OFF",
            37: "ROUTE_THROUGH_ON",
            38: "ROUTE_THROUGH_OFF",
            39: "ROUTE_TRANSPARENT_ON",
            40: "ROUTE_TRANSPARENT_OFF",
            41: "ROUTE_CHANGE_IMAGE",
            42: "ROUTE_CHANGE_OPACITY",
            43: "ROUTE_CHANGE_BLEND_MODE",
            44: "ROUTE_PLAY_SE",
            45: "ROUTE_SCRIPT",
        }

        COMMAND_NAMES = {
            0: 'Null',
            101: 'Show Text',
            102: 'Show Choices',
            103: 'Input Number',
            104: 'Choose Item',
            105: 'Show Scrolling Text',
            108: 'Comment',
            111: 'Conditional Branch',
            112: 'Loop',
            113: 'Break Loop',
            115: 'Exit Event Processing',
            117: 'Common Event',
            118: 'Label',
            119: 'Jump To Label',
            121: 'Control Switches',
            122: 'Control Variables',
            123: 'Control Self Switch',
            124: 'Control Timer',
            125: 'Change Gold',
            126: 'Change Items',
            127: 'Change Weapons',
            128: 'Change Armors',
            129: 'Change Party Member',
            132: 'Change Battle BGM',
            133: 'Change Victory ME',
            134: 'Change Save Access',
            135: 'Toggle Menu Access',
            136: 'Change Encounter Disable',
            137: 'Change Formation Access',
            138: 'Change Window Color',
            139: 'Change Defeat ME',
            140: 'Change Vehicle BGM',
            201: 'Transfer Map',
            203: 'Set Event Location',
            204: 'Scroll Map',
            205: 'Set Movement Route',
            211: 'Change Transparency',
            212: 'Show Character Animation',
            213: 'Show Balloon Icon',
            214: 'Erase Event',
            216: 'Change Player Followers',
            221: 'Fade Out',
            222: 'Fade In',
            223: 'Tint Screen',
            224: 'Flash Screen',
            225: 'Shake Scren',
            230: 'Pause',
            231: 'Show Picture',
            232: 'Move Picture',
            234: 'Tint Picture',
            235: 'Erase Picture',
            236: 'Set Weather Effect',
            241: 'Play BGM',
            242: 'Fadeout BGM',
            243: 'Save BGM',
            244: 'Resume BGM',
            245: 'Play BGS',
            246: 'Fadeout BGS',
            249: 'Play ME',
            250: 'Play SE',
            251: 'Stop SE',
            261: 'Play Movie',
            282: 'Change Tileset',
            284: 'Change Parallax',
            301: 'Battle',
            302: 'Shop',
            303: 'Name Input Processing',
            311: 'Change HP',
            312: 'Change MP',
            313: 'Change State',
            314: 'Recover All',
            315: 'Change EXP',
            316: 'Change Level',
            317: 'Change Parameter',
            318: 'Change Skill',
            319: 'Change Equipment',
            320: 'Change Name',
            321: 'Change Class',
            322: 'Change Actor Images',
            323: 'Change Vehicle Image',
            324: 'Change Nickname',
            325: 'Change Profile',
            326: 'Change TP',
            331: 'Change Enemy HP',
            332: 'Change Enemy MP',
            333: 'Change Enemy State',
            334: 'Enemy Recover All',
            335: 'Enemy Appear',
            336: 'Enemy Transform',
            337: 'Show Battle Animation',
            339: 'Force Action',
            340: 'Abort Battle',
            342: 'Change Enemy TP',
            351: 'Open Menu Screen',
            352: 'Open Save Screen',
            353: 'Game Over',
            354: 'Return to Title',
            355: 'Script',
            356: 'Plugin Command',
            401: 'Show Text Continuation',
            402: 'When',
            403: 'When Cancel',
            404: 'UNKNOWN',
            405: 'Scrolling Text Continuation',
            408: 'Some Mouse Hover Thing',
            411: 'Else',
            412: 'UNKNOWN',
            413: 'Repeat Above',
            505: 'Movement Route Alternate',
            601: 'On Battle Win',
            602: 'On Battle Escape',
            603: 'On Battle Lose',
            604: 'Dunno, Something Battle Related?',
            655: 'Script Continuation'
        }